language: node_js
node_js:
  - "9.2.0"
script:
  - cd frontend && npm install && npm run clean && npm run build
install:
  - npm install -g firebase-tools preact-cli
after-success:
  - firebase deploy --only functions,hosting --project wds-event-tool --token $FIREBASE_TOKEN
branches:
  only:
  - master
